# Generated by Django 3.1.2 on 2020-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghost',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ghost',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ghost',
            name='origin',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
