# Generated by Django 3.1.2 on 2020-11-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghosts', '0002_auto_20201102_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghost',
            name='first_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ghost',
            name='last_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
